---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: kadras-sync
  namespace: kadras-system
  annotations:
    kapp.k14s.io/change-rule.service-account: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-installer
  syncPeriod: 1m0s
  fetch:
  - git:
      url: https://github.com/thomasvitale/kadras-platform-gitops
      ref: main
      subPath: clusters/staging
  template:
  - ytt: {}
  - kbld: {}
  deploy:
  - kapp: {}
