---
apiVersion: v1
kind: Namespace
metadata:
  name: kadras-system
  annotations:
    kapp.k14s.io/change-group: serviceaccount

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kadras-installer
  namespace: kadras-system
  annotations:
    kapp.k14s.io/change-group: serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kadras-installer
  annotations:
    kapp.k14s.io/change-group: serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kadras-installer
  namespace: kadras-system
