---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: kadras-packages
  namespace: kadras-packages
  annotations:
    kapp.k14s.io/change-group: package-repo
spec:
  fetch:
    imgpkgBundle:
      image: ghcr.io/kadras-io/kadras-packages:0.13.0-RC1
