---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: engineering-platform
  namespace: kadras-system
  annotations:
    kapp.k14s.io/change-rule.package-repo: upsert after upserting package-repo
spec:
  packageRef:
    refName: engineering-platform.packages.kadras.io
    versionSelection:
      constraints: 0.11.0-RC1
      prereleases: {}
  serviceAccountName: kadras-installer
  values:
  - secretRef:
      name: engineering-platform-values
